# Generated by Django 5.2.8 on 2025-11-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='author_request_pending',
            field=models.BooleanField(default=False, help_text='User has requested author role'),
        ),
    ]
